// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteUpdate_Op int32

const (
	RouteUpdate_OP_UNSPECIFIED RouteUpdate_Op = 0
	RouteUpdate_OP_ADD         RouteUpdate_Op = 1
	RouteUpdate_OP_DEL         RouteUpdate_Op = 2
)

// Enum value maps for RouteUpdate_Op.
var (
	RouteUpdate_Op_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "OP_ADD",
		2: "OP_DEL",
	}
	RouteUpdate_Op_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"OP_ADD":         1,
		"OP_DEL":         2,
	}
)

func (x RouteUpdate_Op) Enum() *RouteUpdate_Op {
	p := new(RouteUpdate_Op)
	*p = x
	return p
}

func (x RouteUpdate_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteUpdate_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messages_proto_enumTypes[0].Descriptor()
}

func (RouteUpdate_Op) Type() protoreflect.EnumType {
	return &file_proto_messages_proto_enumTypes[0]
}

func (x RouteUpdate_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteUpdate_Op.Descriptor instead.
func (RouteUpdate_Op) EnumDescriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{3, 0}
}

type ClientRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      []byte                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // 32 bytes public key
	Afs           []*ClientRegisterAF    `protobuf:"bytes,2,rep,name=afs,proto3" json:"afs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRegister) Reset() {
	*x = ClientRegister{}
	mi := &file_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegister) ProtoMessage() {}

func (x *ClientRegister) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegister.ProtoReflect.Descriptor instead.
func (*ClientRegister) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ClientRegister) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *ClientRegister) GetAfs() []*ClientRegisterAF {
	if x != nil {
		return x.Afs
	}
	return nil
}

type ClientRegisterAF struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfName        string                 `protobuf:"bytes,1,opt,name=af_name,json=afName,proto3" json:"af_name,omitempty"`                    // e.g. "v4", "v6", "asia_v4"
	ProbePort     uint32                 `protobuf:"varint,2,opt,name=probe_port,json=probePort,proto3" json:"probe_port,omitempty"`          // UDP
	VxlanDstport  uint32                 `protobuf:"varint,3,opt,name=vxlan_dstport,json=vxlanDstport,proto3" json:"vxlan_dstport,omitempty"` // UDP dstport for VXLAN data plane
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`                             // lower is better
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRegisterAF) Reset() {
	*x = ClientRegisterAF{}
	mi := &file_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRegisterAF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegisterAF) ProtoMessage() {}

func (x *ClientRegisterAF) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegisterAF.ProtoReflect.Descriptor instead.
func (*ClientRegisterAF) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ClientRegisterAF) GetAfName() string {
	if x != nil {
		return x.AfName
	}
	return ""
}

func (x *ClientRegisterAF) GetProbePort() uint32 {
	if x != nil {
		return x.ProbePort
	}
	return 0
}

func (x *ClientRegisterAF) GetVxlanDstport() uint32 {
	if x != nil {
		return x.VxlanDstport
	}
	return 0
}

func (x *ClientRegisterAF) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type RouteUpdateBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*RouteUpdate         `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteUpdateBatch) Reset() {
	*x = RouteUpdateBatch{}
	mi := &file_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpdateBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpdateBatch) ProtoMessage() {}

func (x *RouteUpdateBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpdateBatch.ProtoReflect.Descriptor instead.
func (*RouteUpdateBatch) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *RouteUpdateBatch) GetUpdates() []*RouteUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type RouteUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            RouteUpdate_Op         `protobuf:"varint,1,opt,name=op,proto3,enum=vxlancontroller.RouteUpdate_Op" json:"op,omitempty"`
	Entry         *MacIpEntry            `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteUpdate) Reset() {
	*x = RouteUpdate{}
	mi := &file_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpdate) ProtoMessage() {}

func (x *RouteUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpdate.ProtoReflect.Descriptor instead.
func (*RouteUpdate) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RouteUpdate) GetOp() RouteUpdate_Op {
	if x != nil {
		return x.Op
	}
	return RouteUpdate_OP_UNSPECIFIED
}

func (x *RouteUpdate) GetEntry() *MacIpEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type MacIpEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           []byte                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"` // 6 bytes
	Ip            []byte                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`   // 0 bytes means "unknown"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MacIpEntry) Reset() {
	*x = MacIpEntry{}
	mi := &file_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MacIpEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MacIpEntry) ProtoMessage() {}

func (x *MacIpEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MacIpEntry.ProtoReflect.Descriptor instead.
func (*MacIpEntry) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *MacIpEntry) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *MacIpEntry) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

type ControllerProbeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BatchId           uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"` // controller-generated id for this probe batch
	ProbeTimes        uint32                 `protobuf:"varint,2,opt,name=probe_times,json=probeTimes,proto3" json:"probe_times,omitempty"`
	InProbeIntervalMs uint32                 `protobuf:"varint,3,opt,name=in_probe_interval_ms,json=inProbeIntervalMs,proto3" json:"in_probe_interval_ms,omitempty"`
	ProbeTimeoutMs    uint32                 `protobuf:"varint,4,opt,name=probe_timeout_ms,json=probeTimeoutMs,proto3" json:"probe_timeout_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ControllerProbeRequest) Reset() {
	*x = ControllerProbeRequest{}
	mi := &file_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerProbeRequest) ProtoMessage() {}

func (x *ControllerProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerProbeRequest.ProtoReflect.Descriptor instead.
func (*ControllerProbeRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ControllerProbeRequest) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *ControllerProbeRequest) GetProbeTimes() uint32 {
	if x != nil {
		return x.ProbeTimes
	}
	return 0
}

func (x *ControllerProbeRequest) GetInProbeIntervalMs() uint32 {
	if x != nil {
		return x.InProbeIntervalMs
	}
	return 0
}

func (x *ControllerProbeRequest) GetProbeTimeoutMs() uint32 {
	if x != nil {
		return x.ProbeTimeoutMs
	}
	return 0
}

type ProbeResults struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BatchId        uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	SourceClientId []byte                 `protobuf:"bytes,2,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"` // 32 bytes pubkey
	Peers          []*PeerProbeResults    `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProbeResults) Reset() {
	*x = ProbeResults{}
	mi := &file_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResults) ProtoMessage() {}

func (x *ProbeResults) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResults.ProtoReflect.Descriptor instead.
func (*ProbeResults) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ProbeResults) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *ProbeResults) GetSourceClientId() []byte {
	if x != nil {
		return x.SourceClientId
	}
	return nil
}

func (x *ProbeResults) GetPeers() []*PeerProbeResults {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerProbeResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DstClientId   []byte                 `protobuf:"bytes,1,opt,name=dst_client_id,json=dstClientId,proto3" json:"dst_client_id,omitempty"` // 32 bytes pubkey
	AfResults     []*AFProbeResult       `protobuf:"bytes,2,rep,name=af_results,json=afResults,proto3" json:"af_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerProbeResults) Reset() {
	*x = PeerProbeResults{}
	mi := &file_proto_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerProbeResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerProbeResults) ProtoMessage() {}

func (x *PeerProbeResults) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerProbeResults.ProtoReflect.Descriptor instead.
func (*PeerProbeResults) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{7}
}

func (x *PeerProbeResults) GetDstClientId() []byte {
	if x != nil {
		return x.DstClientId
	}
	return nil
}

func (x *PeerProbeResults) GetAfResults() []*AFProbeResult {
	if x != nil {
		return x.AfResults
	}
	return nil
}

type AFProbeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfName        string                 `protobuf:"bytes,1,opt,name=af_name,json=afName,proto3" json:"af_name,omitempty"`
	LatencyMeanMs float64                `protobuf:"fixed64,2,opt,name=latency_mean_ms,json=latencyMeanMs,proto3" json:"latency_mean_ms,omitempty"` // INF if unreachable
	LatencyStdMs  float64                `protobuf:"fixed64,3,opt,name=latency_std_ms,json=latencyStdMs,proto3" json:"latency_std_ms,omitempty"`
	PacketLoss    float64                `protobuf:"fixed64,4,opt,name=packet_loss,json=packetLoss,proto3" json:"packet_loss,omitempty"` // 0..1
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AFProbeResult) Reset() {
	*x = AFProbeResult{}
	mi := &file_proto_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AFProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AFProbeResult) ProtoMessage() {}

func (x *AFProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AFProbeResult.ProtoReflect.Descriptor instead.
func (*AFProbeResult) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{8}
}

func (x *AFProbeResult) GetAfName() string {
	if x != nil {
		return x.AfName
	}
	return ""
}

func (x *AFProbeResult) GetLatencyMeanMs() float64 {
	if x != nil {
		return x.LatencyMeanMs
	}
	return 0
}

func (x *AFProbeResult) GetLatencyStdMs() float64 {
	if x != nil {
		return x.LatencyStdMs
	}
	return 0
}

func (x *AFProbeResult) GetPacketLoss() float64 {
	if x != nil {
		return x.PacketLoss
	}
	return 0
}

func (x *AFProbeResult) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type ControllerState struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ControllerId           []byte                 `protobuf:"bytes,1,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"` // 32 bytes pubkey
	ClientCount            uint32                 `protobuf:"varint,2,opt,name=client_count,json=clientCount,proto3" json:"client_count,omitempty"`
	LastClientChangeUnixNs int64                  `protobuf:"varint,3,opt,name=last_client_change_unix_ns,json=lastClientChangeUnixNs,proto3" json:"last_client_change_unix_ns,omitempty"`
	Clients                []*ClientInfo          `protobuf:"bytes,4,rep,name=clients,proto3" json:"clients,omitempty"`
	LatencyMatrix          []*LatencyRow          `protobuf:"bytes,5,rep,name=latency_matrix,json=latencyMatrix,proto3" json:"latency_matrix,omitempty"`
	RouteMatrix            []*RouteRow            `protobuf:"bytes,6,rep,name=route_matrix,json=routeMatrix,proto3" json:"route_matrix,omitempty"`
	RouteTable             []*RouteTableEntry     `protobuf:"bytes,7,rep,name=route_table,json=routeTable,proto3" json:"route_table,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ControllerState) Reset() {
	*x = ControllerState{}
	mi := &file_proto_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerState) ProtoMessage() {}

func (x *ControllerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerState.ProtoReflect.Descriptor instead.
func (*ControllerState) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ControllerState) GetControllerId() []byte {
	if x != nil {
		return x.ControllerId
	}
	return nil
}

func (x *ControllerState) GetClientCount() uint32 {
	if x != nil {
		return x.ClientCount
	}
	return 0
}

func (x *ControllerState) GetLastClientChangeUnixNs() int64 {
	if x != nil {
		return x.LastClientChangeUnixNs
	}
	return 0
}

func (x *ControllerState) GetClients() []*ClientInfo {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ControllerState) GetLatencyMatrix() []*LatencyRow {
	if x != nil {
		return x.LatencyMatrix
	}
	return nil
}

func (x *ControllerState) GetRouteMatrix() []*RouteRow {
	if x != nil {
		return x.RouteMatrix
	}
	return nil
}

func (x *ControllerState) GetRouteTable() []*RouteTableEntry {
	if x != nil {
		return x.RouteTable
	}
	return nil
}

type ClientInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       []byte                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // 32 bytes pubkey
	Endpoints      []*ClientEndpoint      `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	LastSeenUnixNs int64                  `protobuf:"varint,3,opt,name=last_seen_unix_ns,json=lastSeenUnixNs,proto3" json:"last_seen_unix_ns,omitempty"`
	AdditionalCost float64                `protobuf:"fixed64,4,opt,name=additional_cost,json=additionalCost,proto3" json:"additional_cost,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_proto_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ClientInfo) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *ClientInfo) GetEndpoints() []*ClientEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ClientInfo) GetLastSeenUnixNs() int64 {
	if x != nil {
		return x.LastSeenUnixNs
	}
	return 0
}

func (x *ClientInfo) GetAdditionalCost() float64 {
	if x != nil {
		return x.AdditionalCost
	}
	return 0
}

type ClientEndpoint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AfName            string                 `protobuf:"bytes,1,opt,name=af_name,json=afName,proto3" json:"af_name,omitempty"`
	Ip                []byte                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"` // 4 or 16 bytes
	ProbePort         uint32                 `protobuf:"varint,3,opt,name=probe_port,json=probePort,proto3" json:"probe_port,omitempty"`
	CommunicationPort uint32                 `protobuf:"varint,4,opt,name=communication_port,json=communicationPort,proto3" json:"communication_port,omitempty"` // from TCP remote port
	VxlanDstport      uint32                 `protobuf:"varint,5,opt,name=vxlan_dstport,json=vxlanDstport,proto3" json:"vxlan_dstport,omitempty"`
	Priority          int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientEndpoint) Reset() {
	*x = ClientEndpoint{}
	mi := &file_proto_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEndpoint) ProtoMessage() {}

func (x *ClientEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEndpoint.ProtoReflect.Descriptor instead.
func (*ClientEndpoint) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ClientEndpoint) GetAfName() string {
	if x != nil {
		return x.AfName
	}
	return ""
}

func (x *ClientEndpoint) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *ClientEndpoint) GetProbePort() uint32 {
	if x != nil {
		return x.ProbePort
	}
	return 0
}

func (x *ClientEndpoint) GetCommunicationPort() uint32 {
	if x != nil {
		return x.CommunicationPort
	}
	return 0
}

func (x *ClientEndpoint) GetVxlanDstport() uint32 {
	if x != nil {
		return x.VxlanDstport
	}
	return 0
}

func (x *ClientEndpoint) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type LatencyRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcClientId   []byte                 `protobuf:"bytes,1,opt,name=src_client_id,json=srcClientId,proto3" json:"src_client_id,omitempty"`
	Entries       []*SelectedLatency     `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyRow) Reset() {
	*x = LatencyRow{}
	mi := &file_proto_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyRow) ProtoMessage() {}

func (x *LatencyRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyRow.ProtoReflect.Descriptor instead.
func (*LatencyRow) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{12}
}

func (x *LatencyRow) GetSrcClientId() []byte {
	if x != nil {
		return x.SrcClientId
	}
	return nil
}

func (x *LatencyRow) GetEntries() []*SelectedLatency {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SelectedLatency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DstClientId   []byte                 `protobuf:"bytes,1,opt,name=dst_client_id,json=dstClientId,proto3" json:"dst_client_id,omitempty"`
	AfName        string                 `protobuf:"bytes,2,opt,name=af_name,json=afName,proto3" json:"af_name,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectedLatency) Reset() {
	*x = SelectedLatency{}
	mi := &file_proto_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectedLatency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectedLatency) ProtoMessage() {}

func (x *SelectedLatency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectedLatency.ProtoReflect.Descriptor instead.
func (*SelectedLatency) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{13}
}

func (x *SelectedLatency) GetDstClientId() []byte {
	if x != nil {
		return x.DstClientId
	}
	return nil
}

func (x *SelectedLatency) GetAfName() string {
	if x != nil {
		return x.AfName
	}
	return ""
}

func (x *SelectedLatency) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type RouteRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcClientId   []byte                 `protobuf:"bytes,1,opt,name=src_client_id,json=srcClientId,proto3" json:"src_client_id,omitempty"`
	Entries       []*RouteEntry          `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRow) Reset() {
	*x = RouteRow{}
	mi := &file_proto_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRow) ProtoMessage() {}

func (x *RouteRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRow.ProtoReflect.Descriptor instead.
func (*RouteRow) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{14}
}

func (x *RouteRow) GetSrcClientId() []byte {
	if x != nil {
		return x.SrcClientId
	}
	return nil
}

func (x *RouteRow) GetEntries() []*RouteEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RouteEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DstClientId     []byte                 `protobuf:"bytes,1,opt,name=dst_client_id,json=dstClientId,proto3" json:"dst_client_id,omitempty"`
	NexthopClientId []byte                 `protobuf:"bytes,2,opt,name=nexthop_client_id,json=nexthopClientId,proto3" json:"nexthop_client_id,omitempty"` // 32 bytes, empty if unreachable
	AfName          string                 `protobuf:"bytes,3,opt,name=af_name,json=afName,proto3" json:"af_name,omitempty"`                              // src->nexthop AF
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouteEntry) Reset() {
	*x = RouteEntry{}
	mi := &file_proto_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEntry) ProtoMessage() {}

func (x *RouteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEntry.ProtoReflect.Descriptor instead.
func (*RouteEntry) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{15}
}

func (x *RouteEntry) GetDstClientId() []byte {
	if x != nil {
		return x.DstClientId
	}
	return nil
}

func (x *RouteEntry) GetNexthopClientId() []byte {
	if x != nil {
		return x.NexthopClientId
	}
	return nil
}

func (x *RouteEntry) GetAfName() string {
	if x != nil {
		return x.AfName
	}
	return ""
}

type RouteTableEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           []byte                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"` // 6 bytes
	Ip            []byte                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`   // 0 bytes ok
	Owners        []*RouteOwner          `protobuf:"bytes,3,rep,name=owners,proto3" json:"owners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTableEntry) Reset() {
	*x = RouteTableEntry{}
	mi := &file_proto_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTableEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTableEntry) ProtoMessage() {}

func (x *RouteTableEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTableEntry.ProtoReflect.Descriptor instead.
func (*RouteTableEntry) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{16}
}

func (x *RouteTableEntry) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *RouteTableEntry) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *RouteTableEntry) GetOwners() []*RouteOwner {
	if x != nil {
		return x.Owners
	}
	return nil
}

type RouteOwner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      []byte                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ExpireUnixNs  int64                  `protobuf:"varint,2,opt,name=expire_unix_ns,json=expireUnixNs,proto3" json:"expire_unix_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteOwner) Reset() {
	*x = RouteOwner{}
	mi := &file_proto_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteOwner) ProtoMessage() {}

func (x *RouteOwner) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteOwner.ProtoReflect.Descriptor instead.
func (*RouteOwner) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{17}
}

func (x *RouteOwner) GetClientId() []byte {
	if x != nil {
		return x.ClientId
	}
	return nil
}

func (x *RouteOwner) GetExpireUnixNs() int64 {
	if x != nil {
		return x.ExpireUnixNs
	}
	return 0
}

type ControllerStateUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For simplicity, treat as full replacement (production: could be delta).
	FullReplace   bool             `protobuf:"varint,1,opt,name=full_replace,json=fullReplace,proto3" json:"full_replace,omitempty"`
	State         *ControllerState `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerStateUpdate) Reset() {
	*x = ControllerStateUpdate{}
	mi := &file_proto_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerStateUpdate) ProtoMessage() {}

func (x *ControllerStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerStateUpdate.ProtoReflect.Descriptor instead.
func (*ControllerStateUpdate) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{18}
}

func (x *ControllerStateUpdate) GetFullReplace() bool {
	if x != nil {
		return x.FullReplace
	}
	return false
}

func (x *ControllerStateUpdate) GetState() *ControllerState {
	if x != nil {
		return x.State
	}
	return nil
}

type MulticastForward struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceClientId []byte                 `protobuf:"bytes,1,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"` // 32 bytes pubkey (for sanity / debug)
	Frame          []byte                 `protobuf:"bytes,2,opt,name=frame,proto3" json:"frame,omitempty"`                                           // raw ethernet frame
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MulticastForward) Reset() {
	*x = MulticastForward{}
	mi := &file_proto_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MulticastForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MulticastForward) ProtoMessage() {}

func (x *MulticastForward) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MulticastForward.ProtoReflect.Descriptor instead.
func (*MulticastForward) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{19}
}

func (x *MulticastForward) GetSourceClientId() []byte {
	if x != nil {
		return x.SourceClientId
	}
	return nil
}

func (x *MulticastForward) GetFrame() []byte {
	if x != nil {
		return x.Frame
	}
	return nil
}

type MulticastDeliver struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceClientId []byte                 `protobuf:"bytes,1,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"` // original source
	Frame          []byte                 `protobuf:"bytes,2,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MulticastDeliver) Reset() {
	*x = MulticastDeliver{}
	mi := &file_proto_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MulticastDeliver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MulticastDeliver) ProtoMessage() {}

func (x *MulticastDeliver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MulticastDeliver.ProtoReflect.Descriptor instead.
func (*MulticastDeliver) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{20}
}

func (x *MulticastDeliver) GetSourceClientId() []byte {
	if x != nil {
		return x.SourceClientId
	}
	return nil
}

func (x *MulticastDeliver) GetFrame() []byte {
	if x != nil {
		return x.Frame
	}
	return nil
}

type ProbeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BatchId            uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Seq                uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`                                              // 0..probe_times-1
	ProbeId            uint64                 `protobuf:"varint,3,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`                       // unique id per probe packet
	SourceClientId     []byte                 `protobuf:"bytes,4,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"` // 32 bytes pubkey
	SrcTimestampUnixNs int64                  `protobuf:"varint,5,opt,name=src_timestamp_unix_ns,json=srcTimestampUnixNs,proto3" json:"src_timestamp_unix_ns,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_proto_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{21}
}

func (x *ProbeRequest) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *ProbeRequest) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ProbeRequest) GetProbeId() uint64 {
	if x != nil {
		return x.ProbeId
	}
	return 0
}

func (x *ProbeRequest) GetSourceClientId() []byte {
	if x != nil {
		return x.SourceClientId
	}
	return nil
}

func (x *ProbeRequest) GetSrcTimestampUnixNs() int64 {
	if x != nil {
		return x.SrcTimestampUnixNs
	}
	return 0
}

type ProbeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BatchId            uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Seq                uint32                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	ProbeId            uint64                 `protobuf:"varint,3,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	SourceClientId     []byte                 `protobuf:"bytes,4,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"` // requester
	DstTimestampUnixNs int64                  `protobuf:"varint,5,opt,name=dst_timestamp_unix_ns,json=dstTimestampUnixNs,proto3" json:"dst_timestamp_unix_ns,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_proto_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{22}
}

func (x *ProbeResponse) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *ProbeResponse) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ProbeResponse) GetProbeId() uint64 {
	if x != nil {
		return x.ProbeId
	}
	return 0
}

func (x *ProbeResponse) GetSourceClientId() []byte {
	if x != nil {
		return x.SourceClientId
	}
	return nil
}

func (x *ProbeResponse) GetDstTimestampUnixNs() int64 {
	if x != nil {
		return x.DstTimestampUnixNs
	}
	return 0
}

var File_proto_messages_proto protoreflect.FileDescriptor

const file_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messages.proto\x12\x0fvxlancontroller\"b\n" +
	"\x0eClientRegister\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\fR\bclientId\x123\n" +
	"\x03afs\x18\x02 \x03(\v2!.vxlancontroller.ClientRegisterAFR\x03afs\"\x8b\x01\n" +
	"\x10ClientRegisterAF\x12\x17\n" +
	"\aaf_name\x18\x01 \x01(\tR\x06afName\x12\x1d\n" +
	"\n" +
	"probe_port\x18\x02 \x01(\rR\tprobePort\x12#\n" +
	"\rvxlan_dstport\x18\x03 \x01(\rR\fvxlanDstport\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\"J\n" +
	"\x10RouteUpdateBatch\x126\n" +
	"\aupdates\x18\x01 \x03(\v2\x1c.vxlancontroller.RouteUpdateR\aupdates\"\xa3\x01\n" +
	"\vRouteUpdate\x12/\n" +
	"\x02op\x18\x01 \x01(\x0e2\x1f.vxlancontroller.RouteUpdate.OpR\x02op\x121\n" +
	"\x05entry\x18\x02 \x01(\v2\x1b.vxlancontroller.MacIpEntryR\x05entry\"0\n" +
	"\x02Op\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06OP_ADD\x10\x01\x12\n" +
	"\n" +
	"\x06OP_DEL\x10\x02\".\n" +
	"\n" +
	"MacIpEntry\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\fR\x03mac\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\fR\x02ip\"\xaf\x01\n" +
	"\x16ControllerProbeRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12\x1f\n" +
	"\vprobe_times\x18\x02 \x01(\rR\n" +
	"probeTimes\x12/\n" +
	"\x14in_probe_interval_ms\x18\x03 \x01(\rR\x11inProbeIntervalMs\x12(\n" +
	"\x10probe_timeout_ms\x18\x04 \x01(\rR\x0eprobeTimeoutMs\"\x8c\x01\n" +
	"\fProbeResults\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12(\n" +
	"\x10source_client_id\x18\x02 \x01(\fR\x0esourceClientId\x127\n" +
	"\x05peers\x18\x03 \x03(\v2!.vxlancontroller.PeerProbeResultsR\x05peers\"u\n" +
	"\x10PeerProbeResults\x12\"\n" +
	"\rdst_client_id\x18\x01 \x01(\fR\vdstClientId\x12=\n" +
	"\n" +
	"af_results\x18\x02 \x03(\v2\x1e.vxlancontroller.AFProbeResultR\tafResults\"\xb3\x01\n" +
	"\rAFProbeResult\x12\x17\n" +
	"\aaf_name\x18\x01 \x01(\tR\x06afName\x12&\n" +
	"\x0flatency_mean_ms\x18\x02 \x01(\x01R\rlatencyMeanMs\x12$\n" +
	"\x0elatency_std_ms\x18\x03 \x01(\x01R\flatencyStdMs\x12\x1f\n" +
	"\vpacket_loss\x18\x04 \x01(\x01R\n" +
	"packetLoss\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\"\x91\x03\n" +
	"\x0fControllerState\x12#\n" +
	"\rcontroller_id\x18\x01 \x01(\fR\fcontrollerId\x12!\n" +
	"\fclient_count\x18\x02 \x01(\rR\vclientCount\x12:\n" +
	"\x1alast_client_change_unix_ns\x18\x03 \x01(\x03R\x16lastClientChangeUnixNs\x125\n" +
	"\aclients\x18\x04 \x03(\v2\x1b.vxlancontroller.ClientInfoR\aclients\x12B\n" +
	"\x0elatency_matrix\x18\x05 \x03(\v2\x1b.vxlancontroller.LatencyRowR\rlatencyMatrix\x12<\n" +
	"\froute_matrix\x18\x06 \x03(\v2\x19.vxlancontroller.RouteRowR\vrouteMatrix\x12A\n" +
	"\vroute_table\x18\a \x03(\v2 .vxlancontroller.RouteTableEntryR\n" +
	"routeTable\"\xbc\x01\n" +
	"\n" +
	"ClientInfo\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\fR\bclientId\x12=\n" +
	"\tendpoints\x18\x02 \x03(\v2\x1f.vxlancontroller.ClientEndpointR\tendpoints\x12)\n" +
	"\x11last_seen_unix_ns\x18\x03 \x01(\x03R\x0elastSeenUnixNs\x12'\n" +
	"\x0fadditional_cost\x18\x04 \x01(\x01R\x0eadditionalCost\"\xc8\x01\n" +
	"\x0eClientEndpoint\x12\x17\n" +
	"\aaf_name\x18\x01 \x01(\tR\x06afName\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\fR\x02ip\x12\x1d\n" +
	"\n" +
	"probe_port\x18\x03 \x01(\rR\tprobePort\x12-\n" +
	"\x12communication_port\x18\x04 \x01(\rR\x11communicationPort\x12#\n" +
	"\rvxlan_dstport\x18\x05 \x01(\rR\fvxlanDstport\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\"l\n" +
	"\n" +
	"LatencyRow\x12\"\n" +
	"\rsrc_client_id\x18\x01 \x01(\fR\vsrcClientId\x12:\n" +
	"\aentries\x18\x02 \x03(\v2 .vxlancontroller.SelectedLatencyR\aentries\"m\n" +
	"\x0fSelectedLatency\x12\"\n" +
	"\rdst_client_id\x18\x01 \x01(\fR\vdstClientId\x12\x17\n" +
	"\aaf_name\x18\x02 \x01(\tR\x06afName\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x01R\tlatencyMs\"e\n" +
	"\bRouteRow\x12\"\n" +
	"\rsrc_client_id\x18\x01 \x01(\fR\vsrcClientId\x125\n" +
	"\aentries\x18\x02 \x03(\v2\x1b.vxlancontroller.RouteEntryR\aentries\"u\n" +
	"\n" +
	"RouteEntry\x12\"\n" +
	"\rdst_client_id\x18\x01 \x01(\fR\vdstClientId\x12*\n" +
	"\x11nexthop_client_id\x18\x02 \x01(\fR\x0fnexthopClientId\x12\x17\n" +
	"\aaf_name\x18\x03 \x01(\tR\x06afName\"h\n" +
	"\x0fRouteTableEntry\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\fR\x03mac\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\fR\x02ip\x123\n" +
	"\x06owners\x18\x03 \x03(\v2\x1b.vxlancontroller.RouteOwnerR\x06owners\"O\n" +
	"\n" +
	"RouteOwner\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\fR\bclientId\x12$\n" +
	"\x0eexpire_unix_ns\x18\x02 \x01(\x03R\fexpireUnixNs\"r\n" +
	"\x15ControllerStateUpdate\x12!\n" +
	"\ffull_replace\x18\x01 \x01(\bR\vfullReplace\x126\n" +
	"\x05state\x18\x02 \x01(\v2 .vxlancontroller.ControllerStateR\x05state\"R\n" +
	"\x10MulticastForward\x12(\n" +
	"\x10source_client_id\x18\x01 \x01(\fR\x0esourceClientId\x12\x14\n" +
	"\x05frame\x18\x02 \x01(\fR\x05frame\"R\n" +
	"\x10MulticastDeliver\x12(\n" +
	"\x10source_client_id\x18\x01 \x01(\fR\x0esourceClientId\x12\x14\n" +
	"\x05frame\x18\x02 \x01(\fR\x05frame\"\xb3\x01\n" +
	"\fProbeRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\x12\x19\n" +
	"\bprobe_id\x18\x03 \x01(\x04R\aprobeId\x12(\n" +
	"\x10source_client_id\x18\x04 \x01(\fR\x0esourceClientId\x121\n" +
	"\x15src_timestamp_unix_ns\x18\x05 \x01(\x03R\x12srcTimestampUnixNs\"\xb4\x01\n" +
	"\rProbeResponse\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\rR\x03seq\x12\x19\n" +
	"\bprobe_id\x18\x03 \x01(\x04R\aprobeId\x12(\n" +
	"\x10source_client_id\x18\x04 \x01(\fR\x0esourceClientId\x121\n" +
	"\x15dst_timestamp_unix_ns\x18\x05 \x01(\x03R\x12dstTimestampUnixNsB\x1eZ\x1cvxlan-controller/proto;protob\x06proto3"

var (
	file_proto_messages_proto_rawDescOnce sync.Once
	file_proto_messages_proto_rawDescData []byte
)

func file_proto_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)))
	})
	return file_proto_messages_proto_rawDescData
}

var file_proto_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_messages_proto_goTypes = []any{
	(RouteUpdate_Op)(0),            // 0: vxlancontroller.RouteUpdate.Op
	(*ClientRegister)(nil),         // 1: vxlancontroller.ClientRegister
	(*ClientRegisterAF)(nil),       // 2: vxlancontroller.ClientRegisterAF
	(*RouteUpdateBatch)(nil),       // 3: vxlancontroller.RouteUpdateBatch
	(*RouteUpdate)(nil),            // 4: vxlancontroller.RouteUpdate
	(*MacIpEntry)(nil),             // 5: vxlancontroller.MacIpEntry
	(*ControllerProbeRequest)(nil), // 6: vxlancontroller.ControllerProbeRequest
	(*ProbeResults)(nil),           // 7: vxlancontroller.ProbeResults
	(*PeerProbeResults)(nil),       // 8: vxlancontroller.PeerProbeResults
	(*AFProbeResult)(nil),          // 9: vxlancontroller.AFProbeResult
	(*ControllerState)(nil),        // 10: vxlancontroller.ControllerState
	(*ClientInfo)(nil),             // 11: vxlancontroller.ClientInfo
	(*ClientEndpoint)(nil),         // 12: vxlancontroller.ClientEndpoint
	(*LatencyRow)(nil),             // 13: vxlancontroller.LatencyRow
	(*SelectedLatency)(nil),        // 14: vxlancontroller.SelectedLatency
	(*RouteRow)(nil),               // 15: vxlancontroller.RouteRow
	(*RouteEntry)(nil),             // 16: vxlancontroller.RouteEntry
	(*RouteTableEntry)(nil),        // 17: vxlancontroller.RouteTableEntry
	(*RouteOwner)(nil),             // 18: vxlancontroller.RouteOwner
	(*ControllerStateUpdate)(nil),  // 19: vxlancontroller.ControllerStateUpdate
	(*MulticastForward)(nil),       // 20: vxlancontroller.MulticastForward
	(*MulticastDeliver)(nil),       // 21: vxlancontroller.MulticastDeliver
	(*ProbeRequest)(nil),           // 22: vxlancontroller.ProbeRequest
	(*ProbeResponse)(nil),          // 23: vxlancontroller.ProbeResponse
}
var file_proto_messages_proto_depIdxs = []int32{
	2,  // 0: vxlancontroller.ClientRegister.afs:type_name -> vxlancontroller.ClientRegisterAF
	4,  // 1: vxlancontroller.RouteUpdateBatch.updates:type_name -> vxlancontroller.RouteUpdate
	0,  // 2: vxlancontroller.RouteUpdate.op:type_name -> vxlancontroller.RouteUpdate.Op
	5,  // 3: vxlancontroller.RouteUpdate.entry:type_name -> vxlancontroller.MacIpEntry
	8,  // 4: vxlancontroller.ProbeResults.peers:type_name -> vxlancontroller.PeerProbeResults
	9,  // 5: vxlancontroller.PeerProbeResults.af_results:type_name -> vxlancontroller.AFProbeResult
	11, // 6: vxlancontroller.ControllerState.clients:type_name -> vxlancontroller.ClientInfo
	13, // 7: vxlancontroller.ControllerState.latency_matrix:type_name -> vxlancontroller.LatencyRow
	15, // 8: vxlancontroller.ControllerState.route_matrix:type_name -> vxlancontroller.RouteRow
	17, // 9: vxlancontroller.ControllerState.route_table:type_name -> vxlancontroller.RouteTableEntry
	12, // 10: vxlancontroller.ClientInfo.endpoints:type_name -> vxlancontroller.ClientEndpoint
	14, // 11: vxlancontroller.LatencyRow.entries:type_name -> vxlancontroller.SelectedLatency
	16, // 12: vxlancontroller.RouteRow.entries:type_name -> vxlancontroller.RouteEntry
	18, // 13: vxlancontroller.RouteTableEntry.owners:type_name -> vxlancontroller.RouteOwner
	10, // 14: vxlancontroller.ControllerStateUpdate.state:type_name -> vxlancontroller.ControllerState
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_messages_proto_init() }
func file_proto_messages_proto_init() {
	if File_proto_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_proto_depIdxs,
		EnumInfos:         file_proto_messages_proto_enumTypes,
		MessageInfos:      file_proto_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_proto = out.File
	file_proto_messages_proto_goTypes = nil
	file_proto_messages_proto_depIdxs = nil
}
