name: ci

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Go test
        run: go test ./...

      - name: Go build
        run: |
          go build ./cmd/controller
          go build ./cmd/client

